#pragma once
// Auto-gerado do cert TLS viper-keysb (192.168.20.200), EC P-256, IP em iPAddress+DNS SAN.
#define PQC_CERT_READY

const char PQC_SERVER_CERT[] = R"===(
-----BEGIN CERTIFICATE-----
MIIB8jCCAZmgAwIBAgIUNVzcS52EIS6qwS4T8goL43M84tYwCgYIKoZIzj0EAwIw
NjELMAkGA1UEBhMCUFQxETAPBgNVBAoMCE1TSS1URVNFMRQwEgYDVQQDDAt2aXBl
ci1rZXlzYjAeFw0yNjA3MTMwMjQ3MzFaFw0zNjA3MTAwMjQ3MzFaMDYxCzAJBgNV
BAYTAlBUMREwDwYDVQQKDAhNU0ktVEVTRTEUMBIGA1UEAwwLdmlwZXIta2V5c2Iw
WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAS+mR7ASM0/p93A2+IxAWcSEDNAIZn2
lulyucVNv/yZRU9zo8yGGtHBqRJKvN3YpBjAAdT0fIhPOZplf1OG+eWjo4GEMIGB
MB0GA1UdDgQWBBSNewSz1JVCyD4+LMjlLjuthiwA2zAPBgNVHRMBAf8EBTADAQH/
MA4GA1UdDwEB/wQEAwIChDA/BgNVHREEODA2hwTAqBTIggt2aXBlci1rZXlzYoIR
dmlwZXIta2V5c2IubG9jYWyCDjE5Mi4xNjguMjAuMjAwMAoGCCqGSM49BAMCA0cA
MEQCICYo10eYYw/2waDIh8gRB633CK+GbYvezinGcuvg5riMAiBbeIE/SAnOXgxv
Pdz2OEwIhx+KRI+sAGKesZ/sBAWuoQ==
-----END CERTIFICATE-----
)===";
