#pragma once
// Auto-gerado do cert TLS viper-pki-c (192.168.30.200), EC P-256, IP em iPAddress+DNS SAN.
#define CLASSICAL_CERT_READY

const char CLASSICAL_SERVER_CERT[] = R"===(
-----BEGIN CERTIFICATE-----
MIIB9DCCAZmgAwIBAgIUUY2GGwe1ARW4ya2m1HR6d/BRFjMwCgYIKoZIzj0EAwIw
NjELMAkGA1UEBhMCUFQxETAPBgNVBAoMCE1TSS1URVNFMRQwEgYDVQQDDAt2aXBl
ci1wa2ktYzAeFw0yNjA3MTMwMjQyNDVaFw0zNjA3MTAwMjQyNDVaMDYxCzAJBgNV
BAYTAlBUMREwDwYDVQQKDAhNU0ktVEVTRTEUMBIGA1UEAwwLdmlwZXItcGtpLWMw
WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQ1USrvuTX4jgqssQ8YPCgLGWp2Z/Kn
joxagOFPgsxW8+TPILLRgG59szrGzxOJDB7WQfHRrnwlX/QsQTq9+JBio4GEMIGB
MB0GA1UdDgQWBBS9okb0NFq1CAEUJuWiBWZFOu9LdTAPBgNVHRMBAf8EBTADAQH/
MA4GA1UdDwEB/wQEAwIChDA/BgNVHREEODA2hwTAqB7Iggt2aXBlci1wa2ktY4IR
dmlwZXItcGtpLWMubG9jYWyCDjE5Mi4xNjguMzAuMjAwMAoGCCqGSM49BAMCA0kA
MEYCIQCRjqFoHn/tmL2PVgfBoY05/a9DGxP+Jceg5ALsX5AiVQIhAM3vcbo4khoG
de2mFS+WwjuNtM0D7FMoWSax0OodN1g7
-----END CERTIFICATE-----
)===";
